"use client";

import { AUTONOMY } from "@/lib/archetypes";

function buildMarkdown({ productName, layers, autonomy, archetype, scores }) {
  const { stackDepth, surfaceCoverage } = scores;
  const autonomyOpt = AUTONOMY.find((a) => a.value === autonomy);
  const date = new Date().toISOString().split("T")[0];

  return `# AI Architecture Scoring Card

**Product:** ${productName}
**Generated:** ${date}

---

## Layer Scoring

| Layer   | Present |
|---------|---------|
| Dev     | ${layers.dev} |
| Arch    | ${layers.arch} |
| Engine  | ${layers.engine} |
| Feature | ${layers.feature} |
| UI      | ${layers.ui} |

**Stack Depth:** ${stackDepth} / 3
**Surface Coverage:** ${surfaceCoverage} / 2

---

## Classification

**Archetype:** ${archetype.name}
${archetype.desc}

**Autonomy Level:** ${autonomyOpt.label} (${autonomy}/3)
${autonomyOpt.desc}

---

## AI Prompt

Use the following prompt with Claude, ChatGPT, or any AI assistant to generate
an Excel or Google Sheets version of this scoring card:

> Create a spreadsheet scoring card for an AI system classification.
> Product name: ${productName}
> Layer scores (1=present, 0=absent): Dev=${layers.dev}, Arch=${layers.arch}, Engine=${layers.engine}, Feature=${layers.feature}, UI=${layers.ui}
> Stack Depth: ${stackDepth}/3, Surface Coverage: ${surfaceCoverage}/2
> Archetype: ${archetype.name} — ${archetype.desc}
> Autonomy: ${autonomyOpt.label} (${autonomy}/3) — ${autonomyOpt.desc}
>
> Build a formatted spreadsheet with: (1) a binary layer matrix with colour coding,
> (2) computed scores, (3) archetype classification with description,
> (4) autonomy level with definition, and (5) a notes column for the user to fill in.

---

*Generated by AI Architecture Taxonomy — davidfacer.com*
`;
}

export default function DownloadButton({ productName, layers, autonomy, archetype, scores }) {
  function handleDownload() {
    const markdown = buildMarkdown({ productName, layers, autonomy, archetype, scores });
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    const safeName = (productName || "scoring-card").toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
    a.download = `${safeName}-ai-architecture-scoring-card.md`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <button
      type="button"
      onClick={handleDownload}
      className="px-4 py-2 rounded-md text-sm font-medium border border-hairline bg-panel text-smoke hover:border-brass hover:text-brass transition-colors"
    >
      Download scoring card
    </button>
  );
}
